cargo-features = ["edition2024"]

[package]
name = "apollo-rust-client"
version = "0.3.2"
edition = "2024"
license = "Apache-2.0"
description = "A Rust client for Apollo configuration center"
authors = ["Qian Qiao <qian.qiao@pm.me>"]
repository = "https://github.com/qqiao/apollo-rust-client"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-std = { version = "1.13.1", features = ["tokio1"] }
async-trait = "0.1"
base64 = "0.22.1"
cfg-if = "1.0.0"
futures = "0.3.31"
hmac = "0.12.1"
log = "0.4.27"
reqwest = { version = "0.12.15", default-features = false, features = ["json"] }
serde_json = "1.0.140"
sha1 = "0.10.6"
thiserror = "2.0.12"
tokio = { version = "1", default-features = false, features = ["rt", "sync", "macros", "time"] }
chrono = "0.4.41"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
url = "2.5.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
chrono = { version = "0.4.41", features = ["wasmbind"] }
gloo-timers = "0.3.0"
wasm-bindgen-test = "0.3.50"
wasm-logger = "0.2.0"
reqwest = { version = "0.12.15", default-features = false, features = ["json"] }
mio = { version = "1.0.3", default-features = false, features = ["os-poll"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "1"
# Be conservative: start with features known to be used by the library or generally safe.
# If "full" was genuinely needed by the library on native, use that.
# For now, let's try a more restricted set and see if native tests still pass.
# If native tests break due to missing tokio features, we can add more here.
# The key features from "full" that are often problematic for WASM are "net", "process", "signal".
# Let's add back common ones but exclude those initially.
features = ["rt", "rt-multi-thread", "sync", "macros", "time", "io-util"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.reqwest]
version = "0.12.15"
default-features = false
features = ["rustls-tls-native-roots", "stream", "json", "blocking"]

[dev-dependencies]
async-std = { version = "1.12", features = ["attributes"] }
env_logger = "0.11.8"
lazy_static = "1.5.0"
mockito = "1.4.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] } # Added rt-multi-thread for tokio::test
serde = { version = "1.0", features = ["derive"] } # Added for test utilities

[profile.dev]
debug = true
