[package]
name = "apollo-rust-client"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
futures = "0.3.31"
hex = "0.4.3"
hmac = "0.12.1"
log = "0.4.27"
reqwest = "0.12.15"
serde_json = "1.0.140"
sha1 = "0.10.6"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros"] }
url = "2.5.4"

[dev-dependencies]
env_logger = "0.11.8"
