[package]
name = "apollo-rust-client"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
log = "0.4.27"
reqwest = "0.12.15"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros"] }

[dev-dependencies]
env_logger = "0.11.8"
