name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build
        run: scripts/build.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust toolchain
        run: rustup update
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Run tests
        run: scripts/test.sh
